# Generated by Django 4.1.6 on 2023-06-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('wilayah', models.CharField(max_length=100)),
                ('jumlah_bayi_lahir', models.IntegerField()),
                ('kondisi_bayi', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Data2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('wilayah', models.CharField(max_length=100)),
                ('jumlah_bayi_lahir', models.IntegerField()),
                ('kondisi_bayi', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Data2020',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('wilayah', models.CharField(max_length=100)),
                ('jumlah_bayi_lahir', models.IntegerField()),
                ('kondisi_bayi', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
